ALTER TABLE transfer_inquiries
  ADD COLUMN IF NOT EXISTS luggage_large INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS luggage_medium INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS luggage_carry_on INTEGER NOT NULL DEFAULT 0;
